// Code is generated by ucloud-model, DO NOT EDIT IT.

package ucloudstack

import (
	"github.com/ucloud/ucloud-sdk-go/ucloud/request"
	"github.com/ucloud/ucloud-sdk-go/ucloud/response"
)

// BindAlarmTemplateRequest is request schema for BindAlarmTemplate action
type BindAlarmTemplateRequest struct {
	request.CommonBase

	// [公共参数] 地域。枚举值： cn，表示中国；
	// Region *string `required:"true"`

	// [公共参数] 可用区。枚举值：zone-01，表示中国；
	// Zone *string `required:"true"`

	// 告警模板ID
	AlarmTemplateID *string `required:"true"`

	// 【数组】告警模板ID。调用方式举例：ResourceIDs.0=“one-id”、ResourceIDs.1=“two-id”。
	ResourceIDs []string `required:"true"`

	// 资源类型。VM：虚拟机, LB:负载均衡, NATGW：nat网关;EIP:弹性IP
	ResourceType *string `required:"true"`
}

// BindAlarmTemplateResponse is response schema for BindAlarmTemplate action
type BindAlarmTemplateResponse struct {
	response.CommonBase

	// 返回信息描述
	Message string
}

// NewBindAlarmTemplateRequest will create request of BindAlarmTemplate action.
func (c *UCloudStackClient) NewBindAlarmTemplateRequest() *BindAlarmTemplateRequest {
	req := &BindAlarmTemplateRequest{}

	// setup request with client config
	c.Client.SetupRequest(req)

	// setup retryable with default retry policy (retry for non-create action and common error)
	req.SetRetryable(true)
	return req
}

// BindAlarmTemplate - 绑定告警模板
func (c *UCloudStackClient) BindAlarmTemplate(req *BindAlarmTemplateRequest) (*BindAlarmTemplateResponse, error) {
	var err error
	var res BindAlarmTemplateResponse

	reqCopier := *req

	err = c.Client.InvokeAction("BindAlarmTemplate", &reqCopier, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}
