// Code is generated by ucloud-model, DO NOT EDIT IT.

package ucloudstack

import (
	"github.com/ucloud/ucloud-sdk-go/ucloud/request"
	"github.com/ucloud/ucloud-sdk-go/ucloud/response"
)

// CreateSecurityGroupRuleRequest is request schema for CreateSecurityGroupRule action
type CreateSecurityGroupRuleRequest struct {
	request.CommonBase

	// [公共参数] 地域。枚举值： cn，表示中国；
	// Region *string `required:"true"`

	// [公共参数] 可用区。枚举值：zone-01，表示中国；
	// Zone *string `required:"true"`

	// 【数组】安全组规则。输入有效的规则，调用方式举例：Rule.0=“TCP|23|0.0.0.0/0|ACCEPT|HIGH|1”、Rule.1=“TCP|55|0.0.0.0/0|ACCEPT|HIGH|1”
	Rules []string `required:"true"`

	// 安全组ID
	SGID *string `required:"true"`
}

// CreateSecurityGroupRuleResponse is response schema for CreateSecurityGroupRule action
type CreateSecurityGroupRuleResponse struct {
	response.CommonBase

	// 返回信息描述；
	Message string

	// 创建的安全组规则ID
	SGRuleID string
}

// NewCreateSecurityGroupRuleRequest will create request of CreateSecurityGroupRule action.
func (c *UCloudStackClient) NewCreateSecurityGroupRuleRequest() *CreateSecurityGroupRuleRequest {
	req := &CreateSecurityGroupRuleRequest{}

	// setup request with client config
	c.Client.SetupRequest(req)

	// setup retryable with default retry policy (retry for non-create action and common error)
	req.SetRetryable(false)
	return req
}

// CreateSecurityGroupRule - 创建安全组规则
func (c *UCloudStackClient) CreateSecurityGroupRule(req *CreateSecurityGroupRuleRequest) (*CreateSecurityGroupRuleResponse, error) {
	var err error
	var res CreateSecurityGroupRuleResponse

	reqCopier := *req

	err = c.Client.InvokeAction("CreateSecurityGroupRule", &reqCopier, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}
