// Code is generated by ucloud-model, DO NOT EDIT IT.

package ucloudstack

import (
	"github.com/ucloud/ucloud-sdk-go/ucloud/request"
	"github.com/ucloud/ucloud-sdk-go/ucloud/response"
)

// CreateSecurityGroupRequest is request schema for CreateSecurityGroup action
type CreateSecurityGroupRequest struct {
	request.CommonBase

	// [公共参数] 地域。枚举值： cn，表示中国；
	// Region *string `required:"true"`

	// [公共参数] 可用区。枚举值：zone-01，表示中国；
	// Zone *string `required:"true"`

	// 名称;
	Name *string `required:"true"`

	// 描述;
	Remark *string `required:"false"`

	// 【数组】安全组规则。输入有效的规则，调用方式举例：Rule.0=“TCP|23|0.0.0.0/0|ACCEPT|HIGH|1”、Rule.1=“TCP|55|0.0.0.0/0|ACCEPT|HIGH|1”
	Rule []string `required:"true"`
}

// CreateSecurityGroupResponse is response schema for CreateSecurityGroup action
type CreateSecurityGroupResponse struct {
	response.CommonBase

	// 返回信息描述；
	Message string

	// 创建的安全组ID
	SGID string
}

// NewCreateSecurityGroupRequest will create request of CreateSecurityGroup action.
func (c *UCloudStackClient) NewCreateSecurityGroupRequest() *CreateSecurityGroupRequest {
	req := &CreateSecurityGroupRequest{}

	// setup request with client config
	c.Client.SetupRequest(req)

	// setup retryable with default retry policy (retry for non-create action and common error)
	req.SetRetryable(false)
	return req
}

// CreateSecurityGroup - 创建安全组
func (c *UCloudStackClient) CreateSecurityGroup(req *CreateSecurityGroupRequest) (*CreateSecurityGroupResponse, error) {
	var err error
	var res CreateSecurityGroupResponse

	reqCopier := *req

	err = c.Client.InvokeAction("CreateSecurityGroup", &reqCopier, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}
