// Code is generated by ucloud-model, DO NOT EDIT IT.

package ucloudstack

import (
	"github.com/ucloud/ucloud-sdk-go/ucloud/request"
	"github.com/ucloud/ucloud-sdk-go/ucloud/response"
)

// DeleteSecurityGroupRequest is request schema for DeleteSecurityGroup action
type DeleteSecurityGroupRequest struct {
	request.CommonBase

	// [公共参数] 地域。枚举值： cn，表示中国；
	// Region *string `required:"true"`

	// [公共参数] 可用区。枚举值：zone-01，表示中国；
	// Zone *string `required:"true"`

	// 安全组ID
	SGID *string `required:"true"`
}

// DeleteSecurityGroupResponse is response schema for DeleteSecurityGroup action
type DeleteSecurityGroupResponse struct {
	response.CommonBase

	// 返回信息描述；
	Message string
}

// NewDeleteSecurityGroupRequest will create request of DeleteSecurityGroup action.
func (c *UCloudStackClient) NewDeleteSecurityGroupRequest() *DeleteSecurityGroupRequest {
	req := &DeleteSecurityGroupRequest{}

	// setup request with client config
	c.Client.SetupRequest(req)

	// setup retryable with default retry policy (retry for non-create action and common error)
	req.SetRetryable(true)
	return req
}

// DeleteSecurityGroup - 删除安全组
func (c *UCloudStackClient) DeleteSecurityGroup(req *DeleteSecurityGroupRequest) (*DeleteSecurityGroupResponse, error) {
	var err error
	var res DeleteSecurityGroupResponse

	reqCopier := *req

	err = c.Client.InvokeAction("DeleteSecurityGroup", &reqCopier, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}
