// Code is generated by ucloud-model, DO NOT EDIT IT.

package ucloudstack

import (
	"github.com/ucloud/ucloud-sdk-go/ucloud/request"
	"github.com/ucloud/ucloud-sdk-go/ucloud/response"
)

// DescribeSecurityGroupRequest is request schema for DescribeSecurityGroup action
type DescribeSecurityGroupRequest struct {
	request.CommonBase

	// [公共参数] 地域。
	// Region *string `required:"true"`

	// [公共参数] 可用区。
	// Zone *string `required:"true"`

	// 返回数据长度，默认为20，最大100。
	Limit *int `required:"false"`

	// 列表起始位置偏移量，默认为0。
	Offset *int `required:"false"`

	// 【数组】安全组的 ID。输入有效的 ID。调用方式举例：SGIDs.0=“one-id”、SGIDs.1=“two-id”
	SGIDs []string `required:"false"`
}

// DescribeSecurityGroupResponse is response schema for DescribeSecurityGroup action
type DescribeSecurityGroupResponse struct {
	response.CommonBase

	// 安全组信息列表
	Infos []SGInfo

	// 返回信息描述；
	Message string

	// 安全组的总数
	TotalCount int
}

// NewDescribeSecurityGroupRequest will create request of DescribeSecurityGroup action.
func (c *UCloudStackClient) NewDescribeSecurityGroupRequest() *DescribeSecurityGroupRequest {
	req := &DescribeSecurityGroupRequest{}

	// setup request with client config
	c.Client.SetupRequest(req)

	// setup retryable with default retry policy (retry for non-create action and common error)
	req.SetRetryable(true)
	return req
}

// DescribeSecurityGroup - 查询安全组信息
func (c *UCloudStackClient) DescribeSecurityGroup(req *DescribeSecurityGroupRequest) (*DescribeSecurityGroupResponse, error) {
	var err error
	var res DescribeSecurityGroupResponse

	reqCopier := *req

	err = c.Client.InvokeAction("DescribeSecurityGroup", &reqCopier, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}
