// Code is generated by ucloud-model, DO NOT EDIT IT.

package ucloudstack

import (
	"github.com/ucloud/ucloud-sdk-go/ucloud/request"
	"github.com/ucloud/ucloud-sdk-go/ucloud/response"
)

// ModifyNameAndRemarkRequest is request schema for ModifyNameAndRemark action
type ModifyNameAndRemarkRequest struct {
	request.CommonBase

	// [公共参数] 地域。枚举值： cn，表示中国；
	// Region *string `required:"true"`

	// [公共参数] 可用区。枚举值：zone-01，表示中国；
	// Zone *string `required:"true"`

	// 名称;
	Name *string `required:"true"`

	// 描述;
	Remark *string `required:"false"`

	// 资源ID;
	ResourceID *string `required:"true"`
}

// ModifyNameAndRemarkResponse is response schema for ModifyNameAndRemark action
type ModifyNameAndRemarkResponse struct {
	response.CommonBase

	// 返回信息描述
	Message string
}

// NewModifyNameAndRemarkRequest will create request of ModifyNameAndRemark action.
func (c *UCloudStackClient) NewModifyNameAndRemarkRequest() *ModifyNameAndRemarkRequest {
	req := &ModifyNameAndRemarkRequest{}

	// setup request with client config
	c.Client.SetupRequest(req)

	// setup retryable with default retry policy (retry for non-create action and common error)
	req.SetRetryable(true)
	return req
}

// ModifyNameAndRemark - 修改资源名称和备注
func (c *UCloudStackClient) ModifyNameAndRemark(req *ModifyNameAndRemarkRequest) (*ModifyNameAndRemarkResponse, error) {
	var err error
	var res ModifyNameAndRemarkResponse

	reqCopier := *req

	err = c.Client.InvokeAction("ModifyNameAndRemark", &reqCopier, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}
