// Code is generated by ucloud-model, DO NOT EDIT IT.

package ucloudstack

import (
	"github.com/ucloud/ucloud-sdk-go/ucloud/request"
	"github.com/ucloud/ucloud-sdk-go/ucloud/response"
)

// ResetVMInstancePasswordRequest is request schema for ResetVMInstancePassword action
type ResetVMInstancePasswordRequest struct {
	request.CommonBase

	// [公共参数] 地域。枚举值： cn，表示中国；
	// Region *string `required:"true"`

	// [公共参数] 可用区。枚举值：zone-01，表示中国；
	// Zone *string `required:"true"`

	// 密码
	Password *string `required:"true"`

	// 虚拟机ID
	VMID *string `required:"true"`
}

// ResetVMInstancePasswordResponse is response schema for ResetVMInstancePassword action
type ResetVMInstancePasswordResponse struct {
	response.CommonBase

	// 返回信息描述
	Message string
}

// NewResetVMInstancePasswordRequest will create request of ResetVMInstancePassword action.
func (c *UCloudStackClient) NewResetVMInstancePasswordRequest() *ResetVMInstancePasswordRequest {
	req := &ResetVMInstancePasswordRequest{}

	// setup request with client config
	c.Client.SetupRequest(req)

	// setup retryable with default retry policy (retry for non-create action and common error)
	req.SetRetryable(true)
	return req
}

// ResetVMInstancePassword - 重置虚拟机密码，主机必须开机才可以重置密码
func (c *UCloudStackClient) ResetVMInstancePassword(req *ResetVMInstancePasswordRequest) (*ResetVMInstancePasswordResponse, error) {
	var err error
	var res ResetVMInstancePasswordResponse

	reqCopier := *req

	err = c.Client.InvokeAction("ResetVMInstancePassword", &reqCopier, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}
