// Code is generated by ucloud-model, DO NOT EDIT IT.

package ucloudstack

import (
	"github.com/ucloud/ucloud-sdk-go/ucloud/request"
	"github.com/ucloud/ucloud-sdk-go/ucloud/response"
)

// ResizeVMConfigRequest is request schema for ResizeVMConfig action
type ResizeVMConfigRequest struct {
	request.CommonBase

	// [公共参数] 地域。枚举值： cn，表示中国；
	// Region *string `required:"true"`

	// [公共参数] 可用区。枚举值：zone-01，表示中国；
	// Zone *string `required:"true"`

	// CPU 个数，如 1、2、4、8、16、32、64。
	CPU *int `required:"true"`

	// 内存容量，如 2048、4096、8192、16384、32768、65536、131072。
	Memory *int `required:"true"`

	// 虚拟机ID
	VMID *string `required:"true"`
}

// ResizeVMConfigResponse is response schema for ResizeVMConfig action
type ResizeVMConfigResponse struct {
	response.CommonBase

	// 返回信息描述
	Message string
}

// NewResizeVMConfigRequest will create request of ResizeVMConfig action.
func (c *UCloudStackClient) NewResizeVMConfigRequest() *ResizeVMConfigRequest {
	req := &ResizeVMConfigRequest{}

	// setup request with client config
	c.Client.SetupRequest(req)

	// setup retryable with default retry policy (retry for non-create action and common error)
	req.SetRetryable(true)
	return req
}

// ResizeVMConfig - 修改虚拟机配置
func (c *UCloudStackClient) ResizeVMConfig(req *ResizeVMConfigRequest) (*ResizeVMConfigResponse, error) {
	var err error
	var res ResizeVMConfigResponse

	reqCopier := *req

	err = c.Client.InvokeAction("ResizeVMConfig", &reqCopier, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}
