// Code is generated by ucloud-model, DO NOT EDIT IT.

package ucloudstack

import (
	"github.com/ucloud/ucloud-sdk-go/ucloud/request"
	"github.com/ucloud/ucloud-sdk-go/ucloud/response"
)

// RestartVMInstanceRequest is request schema for RestartVMInstance action
type RestartVMInstanceRequest struct {
	request.CommonBase

	// [公共参数] 地域。枚举值：cn,表示中国；
	// Region *string `required:"true"`

	// [公共参数] 可用区。枚举值：zone-01，表示中国；
	// Zone *string `required:"true"`

	// 虚拟机ID;
	VMID *string `required:"true"`
}

// RestartVMInstanceResponse is response schema for RestartVMInstance action
type RestartVMInstanceResponse struct {
	response.CommonBase

	// 返回信息描述
	Message string
}

// NewRestartVMInstanceRequest will create request of RestartVMInstance action.
func (c *UCloudStackClient) NewRestartVMInstanceRequest() *RestartVMInstanceRequest {
	req := &RestartVMInstanceRequest{}

	// setup request with client config
	c.Client.SetupRequest(req)

	// setup retryable with default retry policy (retry for non-create action and common error)
	req.SetRetryable(true)
	return req
}

// RestartVMInstance - 重启虚拟机
func (c *UCloudStackClient) RestartVMInstance(req *RestartVMInstanceRequest) (*RestartVMInstanceResponse, error) {
	var err error
	var res RestartVMInstanceResponse

	reqCopier := *req

	err = c.Client.InvokeAction("RestartVMInstance", &reqCopier, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}
