// Code is generated by ucloud-model, DO NOT EDIT IT.

package ucloudstack

/*
SGInfo - 安全组信息

this model is auto created by ucloud code generater for open api,
you can also see https://docs.ucloud.cn/api for detail.
*/
type SGInfo struct {

	// 创建时间，时间戳
	CreateTime int

	// 名称
	Name string

	// 地域
	Region string

	// 描述
	Remark string

	// 资源绑定数量
	ResourceCount int

	// 安全组规则。
	Rule []SGRuleInfo

	// 规则数量
	RuleCount int

	// 安全组ID
	SGID string

	// 状态。Creating：创建中,Updating：更新中,Available：有效,Deleted：已删除,Terminating：销毁中,Terminated：已销毁
	Status string

	// 更新时间，时间戳
	UpdateTime int

	// 可用区
	Zone string
}
