// Code is generated by ucloud-model, DO NOT EDIT IT.

package ucloudstack

/*
VPCInfo - VPC信息

this model is auto created by ucloud code generater for open api,
you can also see https://docs.ucloud.cn/api for detail.
*/
type VPCInfo struct {

	// 创建时间，时间戳
	CreateTime int

	// 名称
	Name string

	// 地域。
	Region string

	// 描述
	Remark string

	// 状态；Allocating：申请中,Available：有效,Terminating：销毁中,Terminated：已销毁
	State string

	// 该VPC下拥有的子网数目
	SubnetCount int

	// 该VPC下子网信息。
	SubnetInfos []SubnetInfo

	// 修改时间，时间戳
	UpdateTime int

	// VPC的ID
	VPCID string

	// 可用区
	Zone string
}
