// Code is generated by ucloud-model, DO NOT EDIT IT.

package ucloudstack

/*
DiskInfo - 磁盘信息

this model is auto created by ucloud code generater for open api,
you can also see https://docs.ucloud.cn/api for detail.
*/
type DiskInfo struct {

	// 绑定资源ID
	AttachResourceID string

	// 硬盘计费模式。枚举值：Dynamic，表示小时；Month，表示月；Year，表示年；
	ChargeType string

	// 创建时间。时间戳
	CreateTime int

	// 硬盘ID
	DiskID string

	// 硬盘状态。Creating：创建中,BeingCloned：正在被克隆中,Unbound：已解绑,Unbounding：解绑中,Bounding：绑定中,Bound：已绑定,Upgrading：升级中,Deleting：删除中,Deleted：已删除,Releasing：销毁中,Released：已销毁
	DiskStatus string

	// 过期时间。时间戳
	ExpireTime int

	// 名称
	Name string

	// 地域
	Region string

	// 备注
	Remark string

	// 磁盘类型。例如：Normal,SSD
	SetType string

	// 大小。单位GB
	Size int

	// 可用区
	Zone string
}
