// Code is generated by ucloud-model, DO NOT EDIT IT.

package ucloudstack

/*
SGRuleInfo - 安全组规则信息

this model is auto created by ucloud code generater for open api,
you can also see https://docs.ucloud.cn/api for detail.
*/
type SGRuleInfo struct {

	// 端口号
	DstPort string

	// 方向。1：入，0：出
	IsIn string

	// 优先级。HIGH:高，MEDIUM:中，LOW:低
	Priority string

	// 协议
	ProtocolType string

	// 动作。ACCEPT：接受，DROP：拒绝
	RuleAction string

	// 规则ID
	RuleID string

	// IP或者掩码/段形式。10.0.0.2,10.0.10.10/16
	SrcIP string
}
