// Code is generated by ucloud-model, DO NOT EDIT IT.

package ucloudstack

import (
	"github.com/ucloud/ucloud-sdk-go/ucloud/request"
	"github.com/ucloud/ucloud-sdk-go/ucloud/response"
)

// UnbindAlarmTemplateRequest is request schema for UnbindAlarmTemplate action
type UnbindAlarmTemplateRequest struct {
	request.CommonBase

	// [公共参数] 地域。枚举值： cn，表示中国；
	// Region *string `required:"true"`

	// [公共参数] 可用区。枚举值：zone-01，表示中国；
	// Zone *string `required:"true"`

	// 【数组】资源的 ID。调用方式举例：ResourceIDs.0=“one-id”、ResourceIDs.1=“two-id”。
	ResourceIDs []string `required:"true"`

	// 资源类型。VM：虚拟机, LB:负载均衡, NATGW：nat网关;EIP:弹性网卡
	ResourceType *string `required:"true"`
}

// UnbindAlarmTemplateResponse is response schema for UnbindAlarmTemplate action
type UnbindAlarmTemplateResponse struct {
	response.CommonBase

	// 返回信息描述
	Message string
}

// NewUnbindAlarmTemplateRequest will create request of UnbindAlarmTemplate action.
func (c *UCloudStackClient) NewUnbindAlarmTemplateRequest() *UnbindAlarmTemplateRequest {
	req := &UnbindAlarmTemplateRequest{}

	// setup request with client config
	c.Client.SetupRequest(req)

	// setup retryable with default retry policy (retry for non-create action and common error)
	req.SetRetryable(true)
	return req
}

// UnbindAlarmTemplate - 解绑告警模板
func (c *UCloudStackClient) UnbindAlarmTemplate(req *UnbindAlarmTemplateRequest) (*UnbindAlarmTemplateResponse, error) {
	var err error
	var res UnbindAlarmTemplateResponse

	reqCopier := *req

	err = c.Client.InvokeAction("UnbindAlarmTemplate", &reqCopier, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}
