// Code is generated by ucloud-model, DO NOT EDIT IT.

package ucloudstack

import (
	"github.com/ucloud/ucloud-sdk-go/ucloud/request"
	"github.com/ucloud/ucloud-sdk-go/ucloud/response"
)

// UpdateSecurityGroupRuleRequest is request schema for UpdateSecurityGroupRule action
type UpdateSecurityGroupRuleRequest struct {
	request.CommonBase

	// [公共参数] 地域。枚举值： cn，表示中国；
	// Region *string `required:"true"`

	// [公共参数] 可用区。枚举值：zone-01，表示中国；
	// Zone *string `required:"true"`

	// 【数组】规则。输入有效的 规则。调用方式举例：Rules.0=“TCP|23|0.0.0.0/0|ACCEPT|HIGH|1”、Rules.1=“TCP|55|0.0.0.0/0|ACCEPT|HIGH|1”
	Rules []string `required:"true"`

	// 安全组ID
	SGID *string `required:"true"`
}

// UpdateSecurityGroupRuleResponse is response schema for UpdateSecurityGroupRule action
type UpdateSecurityGroupRuleResponse struct {
	response.CommonBase

	// 返回信息描述；
	Message string
}

// NewUpdateSecurityGroupRuleRequest will create request of UpdateSecurityGroupRule action.
func (c *UCloudStackClient) NewUpdateSecurityGroupRuleRequest() *UpdateSecurityGroupRuleRequest {
	req := &UpdateSecurityGroupRuleRequest{}

	// setup request with client config
	c.Client.SetupRequest(req)

	// setup retryable with default retry policy (retry for non-create action and common error)
	req.SetRetryable(true)
	return req
}

// UpdateSecurityGroupRule - 修改安全组规则
func (c *UCloudStackClient) UpdateSecurityGroupRule(req *UpdateSecurityGroupRuleRequest) (*UpdateSecurityGroupRuleResponse, error) {
	var err error
	var res UpdateSecurityGroupRuleResponse

	reqCopier := *req

	err = c.Client.InvokeAction("UpdateSecurityGroupRule", &reqCopier, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}
